### PR TITLE
Sound

### PR DESCRIPTION
**Pull request by ghostmothv**
sfx sounds + renamed voicelines

### CODE REVIEW

**Review by Wolltoffel — CHANGES_REQUESTED** [review]
Pls refer back to Asset Guidelines for two things:
2.11 Special Rules for Soundfiles
2.1- 2-6

Recheck your commited files and apply the needed changes according to the guidelines

**Comment by ghostmothv** [comment]
updated sfx files and csv table

**Review by Wolltoffel — CHANGES_REQUESTED** [review]
1. Only number things when you need to. When naming files avoid numbers as much as possible. If two files have different names there's no need to have an additional separations layer by numbers. This just makes them more complicated to read
I noticed that in the Experiment Folder (e.g 2_1_pouringWater, 2_2_sizzlingWater).

3. Don't overcomplicate numbering systems like in this case:
1_0_steamHiss.wav
1_0_steamHiss.wav

These two files could be easily changed to steamHiss_0 and steamHiss_1 etc.

4. Convert your  .md ReadMes in normal .txt. It's easier to open the file in this format

5. Put everything that is SFX in one folder on the same layer as music, voicelines and Twine. That makes the file loading in a later stage simpler to manage.

**Comment by ghostmothv** [comment]
put all sfx files in one folder, changed readmes to txt files and updated the csv table

**Comment by ghostmothv** [comment]
merge conflicts solved

**Pull request closed without merging**
